// Curated, well-known named colors with real search intent. Each becomes one
// substantial static page (palette, harmonies, scale, contrast) — not thin hex spam.
export const NAMED_COLORS = [
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'Firebrick', hex: '#B22222' },
  { name: 'Indian Red', hex: '#CD5C5C' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Tomato', hex: '#FF6347' },
  { name: 'Orange Red', hex: '#FF4500' },
  { name: 'Dark Orange', hex: '#FF8C00' },
  { name: 'Orange', hex: '#FFA500' },
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Goldenrod', hex: '#DAA520' },
  { name: 'Dark Goldenrod', hex: '#B8860B' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Khaki', hex: '#F0E68C' },
  { name: 'Dark Khaki', hex: '#BDB76B' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Olive Drab', hex: '#6B8E23' },
  { name: 'Yellow Green', hex: '#9ACD32' },
  { name: 'Green Yellow', hex: '#ADFF2F' },
  { name: 'Chartreuse', hex: '#7FFF00' },
  { name: 'Lawn Green', hex: '#7CFC00' },
  { name: 'Lime Green', hex: '#32CD32' },
  { name: 'Lime', hex: '#00FF00' },
  { name: 'Pale Green', hex: '#98FB98' },
  { name: 'Light Green', hex: '#90EE90' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Green', hex: '#008000' },
  { name: 'Dark Green', hex: '#006400' },
  { name: 'Sea Green', hex: '#2E8B57' },
  { name: 'Medium Sea Green', hex: '#3CB371' },
  { name: 'Mint', hex: '#3EB489' },
  { name: 'Emerald', hex: '#50C878' },
  { name: 'Spring Green', hex: '#00FF7F' },
  { name: 'Aquamarine', hex: '#7FFFD4' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Cadet Blue', hex: '#5F9EA0' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Light Blue', hex: '#ADD8E6' },
  { name: 'Powder Blue', hex: '#B0E0E6' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Deep Sky Blue', hex: '#00BFFF' },
  { name: 'Dodger Blue', hex: '#1E90FF' },
  { name: 'Cornflower Blue', hex: '#6495ED' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Midnight Blue', hex: '#191970' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Medium Purple', hex: '#9370DB' },
  { name: 'Blue Violet', hex: '#8A2BE2' },
  { name: 'Indigo', hex: '#4B0082' },
  { name: 'Dark Violet', hex: '#9400D3' },
  { name: 'Dark Orchid', hex: '#9932CC' },
  { name: 'Medium Orchid', hex: '#BA55D3' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Violet', hex: '#EE82EE' },
  { name: 'Orchid', hex: '#DA70D6' },
  { name: 'Magenta', hex: '#FF00FF' },
  { name: 'Plum', hex: '#DDA0DD' },
  { name: 'Thistle', hex: '#D8BFD8' },
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Hot Pink', hex: '#FF69B4' },
  { name: 'Deep Pink', hex: '#FF1493' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Light Pink', hex: '#FFB6C1' },
  { name: 'Pale Violet Red', hex: '#DB7093' },
  { name: 'Rosy Brown', hex: '#BC8F8F' },
  { name: 'Maroon', hex: '#800000' },
  { name: 'Brown', hex: '#A52A2A' },
  { name: 'Sienna', hex: '#A0522D' },
  { name: 'Saddle Brown', hex: '#8B4513' },
  { name: 'Chocolate', hex: '#D2691E' },
  { name: 'Peru', hex: '#CD853F' },
  { name: 'Sandy Brown', hex: '#F4A460' },
  { name: 'Tan', hex: '#D2B48C' },
  { name: 'Wheat', hex: '#F5DEB3' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Bisque', hex: '#FFE4C4' },
  { name: 'Moccasin', hex: '#FFE4B5' },
  { name: 'Slate Gray', hex: '#708090' },
  { name: 'Dark Slate Gray', hex: '#2F4F4F' },
  { name: 'Gray', hex: '#808080' },
  { name: 'Silver', hex: '#C0C0C0' },
  { name: 'Gainsboro', hex: '#DCDCDC' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' }
];

export const slugify = name => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
